name: Automated tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v3
      - name: setup Python
        uses: action/python@v4
        with:
          python-version: "3.12"
      - name: install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run coffee butik tests
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets. PASSWORD }}
          PASSWORD_TWO: ${{ secrets. PASSWORD_TWO }}
        run:
          pytest --exit-code-from regression || true